### ISSUE TITLE
Constant button events from touchscreen

### ISSUE THREAD

**Issue by Slabity** [hadess/gt9xx#1]
I'm using an HP Stream 7 with kernel 4.0-rc7

The touchscreen constantly reports BTN_TOUCH->0 and BTN_TOUCH->1 events in evtest, which causes ButtonPressed/Released events in X. This makes everything appear to be double tapping unless you touch and release instantaneously.

I've reproduced this on 2 separate HP Stream 7 tablets using both the Fedlet baytrail releases and an up-to-date version of Arch.

**Comment by hadess** [comment]
Bug reports should be sent to the linux-input mailing-list. And please include some debug...
